### ISSUE TITLE
"Unlimited" Feature Broken

### ISSUE THREAD

**Issue by mikesoltis** [backdrop-contrib/blockreference#12]
Steps to create the problem:

Add a block reference called Test3 to a content type called Tab.  Select "Unlimited" for Number of Values in Global Settings.

These errors appear when configuring or editing the Test3 field:

Notice: Undefined property: Node::$roles in user_access() (line 517 of /apache/www/html/smbmc/core/modules/user/user.module).
Warning: Invalid argument supplied for foreach() in user_role_permissions() (line 468 of /apache/www/html/smbmc/core/modules/user/user.module).

Two Types of failures::

1) Select "Autocomplete" for the Block Reference widget type:

When adding or editing Tab content, the "Add Another Item" button shows as expected for the Reference Block field "Test3" (see picture below), but the autocomplete fields do not function correctly - they behave like normal text boxes but don't actually accept a block name when the content is saved.

![autocomplete](https://user-images.githubusercontent.com/78069725/139616107-a6cd016a-4686-4e0b-864c-3a0ac7f73270.png)
 
 
 
2) Select "Select List" (or "Check Boxes") for the Block Reference widget type: 

The "Add Another Item" button does not show for the Test3 field when adding or editing Tab content (see picture below).  

![select](https://user-images.githubusercontent.com/78069725/139617307-965b361f-3399-46c2-ac32-913d9b8680bf.png)

**Comment by olafgrabienski** [comment]
@mikesoltis Thanks for your report! I'm using the module as well and was curious about the mentioned issues, so I tested quickly. My results:

(0) I don't get any error notices.

(1) Indeed, the autocomplete does *not* work as expected. When I start to type the name of a Views block, I don't get any suggestion. In contrast, a token in square brackets like `[views:search-block_1]` will be accepted and saved, if it's the correct one, but it's not obvious where to know about the correct token.

(2) The select list *allows* multiple values. To select more than one value, hold down the `Ctrl` key (`Cmd` on Mac) and click on the items.

**Comment by mikesoltis** [comment]
Thanks for the feedback - 

1) If tokens are entered correctly, it does work - the token strings have to be constructed from module and machine names (multiple machine names separated by "-".  For example, [block:custom_block_name] and [views:block_name-block_3].  Multiple items can be added and they can be rearranged easily by dragging them around.  This mode will work well until something better is in place.

2) Yes, I can select several blocks, but I am not able to drag them into a different order or assign a weight on this interface, making this mode unusable in practice.  It needs an "Add More Items" button (as does the Check Boxes widget).

**Comment by olafgrabienski** [comment]
Regarding your 2nd point, I guess that's how a list widget is supposed to work. At least, the behavior is the same for Taxonomy tags provided by Backdrop core. So, if there's a need to change the order of items, it's better to choose another widget.

**Comment by yorkshire-pudding** [comment]
All the issues in this have been completed in other issues. Autocomplete now works for regular fields so recommend this is used in preference to select list with unlimited fields.
