### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/blockreference#13]
@opi, are you willing to make a new release with this fix (already merged but not included in the latest release)?

 - https://github.com/backdrop-contrib/blockreference/commit/2ea2a3407dc53607fe3657a0443940613c5b7e1c

**Comment by laryn** [comment]
Or alternately here's another approach submitted in a PR, I suppose: https://github.com/backdrop-contrib/blockreference/pull/11/files

**Comment by yorkshire-pudding** [comment]
I'm going to review where we are with all the pull requests and try to get a new release out today or tomorrow.

**Comment by yorkshire-pudding** [comment]
I have created a release with the fixes to date.
