### ISSUE TITLE
Request to become maintainer or co-maintainer

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/blockreference#14]
Hi @opi 

I note that there hasn't been much activity on this module from you for a while.  I'd like to help get this module with all the issues fixed and compatible with PHP 8.  Are you willing for me to become a co-maintainer or to take over the maintainer role on this project?

Thanks
Martin

**Comment by opi** [comment]
I'm OK with your suggestion, as I've got no more time to contribute to backdrop.

**Comment by klonos** [comment]
Thank you for approving @opi (and hello 👋🏼 ) ...sorry that you don't have time to contribute to Backdrop - we miss you! 🙂 

I have now configure access for the repo as per the policy: https://backdropcms.org/news/updated-permissions-policy-for-contributed-projects

@yorkshire-pudding can you please confirm and close this issue if everything works as expected? Thanks.
