### ISSUE TITLE
Use require_once instead of require

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/blockreference#25]
I'm not sure why I haven't seen this before, it's strange... but I just tried to enable this module and had a strange case where it gave a fatal error saying I couldn't redeclare `blockreference_field_info()` but it was previously declared in the same file. I see that this line is using `require` instead of `require_once`:

```
require __DIR__ . '/blockreference.field.inc';
```

Switching it to `require_once` does solve the issue for me.

**Comment by yorkshire-pudding** [comment]
@laryn - are you happy to do a PR?
I haven't seen this so I wonder what conditions cause this.

**Comment by laryn** [comment]
I'm also not sure why I'm seeing this now and never have before... If you'd accept that as a defensive coding solution I'd be happy to make a PR.

**Comment by yorkshire-pudding** [comment]
I'm open to defensive coding, and I can't see any issue with this simple switch.

**Comment by laryn** [comment]
@yorkshire-pudding PR submitted; FYI I included a minor coding standards fix later in the file as well.
