### ISSUE TITLE
Undefined offset in widget form

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/blockreference#6]
Error when going to `node/add/page` after just adding a block ref field while keeping the default settings (uses autocomplete):

> Notice: Undefined offset: 1 in blockreference_field_widget_form() (line 267 of /home/qa/github/backdrop/backdrop/pr/2839/modules/blockreference/blockreference.field.inc).

I also see that the autocomplete doesn't work, it's just a regular field.

**Comment by ghost** [comment]
Here's a PR: https://github.com/backdrop-contrib/blockreference/pull/7
